# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(920, 600)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout.setContentsMargins(11, 11, 11, 0)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_SelectedDevice_WakeUp = QtWidgets.QPushButton(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_SelectedDevice_WakeUp.sizePolicy().hasHeightForWidth())
        self.pushButton_SelectedDevice_WakeUp.setSizePolicy(sizePolicy)
        self.pushButton_SelectedDevice_WakeUp.setObjectName("pushButton_SelectedDevice_WakeUp")
        self.gridLayout.addWidget(self.pushButton_SelectedDevice_WakeUp, 0, 3, 1, 1)
        self.label_SelectDevice = QtWidgets.QLabel(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_SelectDevice.sizePolicy().hasHeightForWidth())
        self.label_SelectDevice.setSizePolicy(sizePolicy)
        self.label_SelectDevice.setObjectName("label_SelectDevice")
        self.gridLayout.addWidget(self.label_SelectDevice, 0, 0, 1, 1)
        self.comboBox_SelectDevice = QtWidgets.QComboBox(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_SelectDevice.sizePolicy().hasHeightForWidth())
        self.comboBox_SelectDevice.setSizePolicy(sizePolicy)
        self.comboBox_SelectDevice.setEditable(False)
        self.comboBox_SelectDevice.setObjectName("comboBox_SelectDevice")
        self.gridLayout.addWidget(self.comboBox_SelectDevice, 0, 1, 1, 1)
        self.label_IpAddress = QtWidgets.QLabel(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_IpAddress.sizePolicy().hasHeightForWidth())
        self.label_IpAddress.setSizePolicy(sizePolicy)
        self.label_IpAddress.setMinimumSize(QtCore.QSize(0, 0))
        self.label_IpAddress.setMaximumSize(QtCore.QSize(120, 16777215))
        self.label_IpAddress.setObjectName("label_IpAddress")
        self.gridLayout.addWidget(self.label_IpAddress, 0, 2, 1, 1)
        self.pushButton_SelectedDevice_Ping = QtWidgets.QPushButton(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_SelectedDevice_Ping.sizePolicy().hasHeightForWidth())
        self.pushButton_SelectedDevice_Ping.setSizePolicy(sizePolicy)
        self.pushButton_SelectedDevice_Ping.setFlat(False)
        self.pushButton_SelectedDevice_Ping.setObjectName("pushButton_SelectedDevice_Ping")
        self.gridLayout.addWidget(self.pushButton_SelectedDevice_Ping, 0, 4, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName("tabWidget")
        self.tabSelected = QtWidgets.QWidget()
        self.tabSelected.setObjectName("tabSelected")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tabSelected)
        self.verticalLayout_5.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_5.setSpacing(6)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_2 = QtWidgets.QFrame(self.tabSelected)
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_4.setContentsMargins(0, 5, 0, 5)
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton_SelectedDevice_Version = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_SelectedDevice_Version.sizePolicy().hasHeightForWidth())
        self.pushButton_SelectedDevice_Version.setSizePolicy(sizePolicy)
        self.pushButton_SelectedDevice_Version.setMinimumSize(QtCore.QSize(88, 0))
        self.pushButton_SelectedDevice_Version.setObjectName("pushButton_SelectedDevice_Version")
        self.horizontalLayout_4.addWidget(self.pushButton_SelectedDevice_Version)
        self.pushButton_SelectedDevice_UpdateStatus = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_SelectedDevice_UpdateStatus.sizePolicy().hasHeightForWidth())
        self.pushButton_SelectedDevice_UpdateStatus.setSizePolicy(sizePolicy)
        self.pushButton_SelectedDevice_UpdateStatus.setMinimumSize(QtCore.QSize(88, 0))
        self.pushButton_SelectedDevice_UpdateStatus.setObjectName("pushButton_SelectedDevice_UpdateStatus")
        self.horizontalLayout_4.addWidget(self.pushButton_SelectedDevice_UpdateStatus)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.verticalLayout_5.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.tabSelected)
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_5.setContentsMargins(0, 5, 0, 5)
        self.horizontalLayout_5.setSpacing(6)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pushButton_SelectedDevice_AudioUpdate = QtWidgets.QPushButton(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_SelectedDevice_AudioUpdate.sizePolicy().hasHeightForWidth())
        self.pushButton_SelectedDevice_AudioUpdate.setSizePolicy(sizePolicy)
        self.pushButton_SelectedDevice_AudioUpdate.setMinimumSize(QtCore.QSize(88, 0))
        self.pushButton_SelectedDevice_AudioUpdate.setObjectName("pushButton_SelectedDevice_AudioUpdate")
        self.horizontalLayout_5.addWidget(self.pushButton_SelectedDevice_AudioUpdate)
        self.pushButton_SelectedDevice_AudioClean = QtWidgets.QPushButton(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_SelectedDevice_AudioClean.sizePolicy().hasHeightForWidth())
        self.pushButton_SelectedDevice_AudioClean.setSizePolicy(sizePolicy)
        self.pushButton_SelectedDevice_AudioClean.setMinimumSize(QtCore.QSize(88, 0))
        self.pushButton_SelectedDevice_AudioClean.setObjectName("pushButton_SelectedDevice_AudioClean")
        self.horizontalLayout_5.addWidget(self.pushButton_SelectedDevice_AudioClean)
        spacerItem1 = QtWidgets.QSpacerItem(689, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.verticalLayout_5.addWidget(self.frame_3)
        self.frame_5 = QtWidgets.QFrame(self.tabSelected)
        self.frame_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_7.setContentsMargins(0, 5, 0, 5)
        self.horizontalLayout_7.setSpacing(6)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.pushButton_SelectedDevice_VideoUpdate = QtWidgets.QPushButton(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_SelectedDevice_VideoUpdate.sizePolicy().hasHeightForWidth())
        self.pushButton_SelectedDevice_VideoUpdate.setSizePolicy(sizePolicy)
        self.pushButton_SelectedDevice_VideoUpdate.setMinimumSize(QtCore.QSize(88, 0))
        self.pushButton_SelectedDevice_VideoUpdate.setObjectName("pushButton_SelectedDevice_VideoUpdate")
        self.horizontalLayout_7.addWidget(self.pushButton_SelectedDevice_VideoUpdate)
        self.pushButton_SelectedDevice_VideoClean = QtWidgets.QPushButton(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_SelectedDevice_VideoClean.sizePolicy().hasHeightForWidth())
        self.pushButton_SelectedDevice_VideoClean.setSizePolicy(sizePolicy)
        self.pushButton_SelectedDevice_VideoClean.setMinimumSize(QtCore.QSize(88, 0))
        self.pushButton_SelectedDevice_VideoClean.setObjectName("pushButton_SelectedDevice_VideoClean")
        self.horizontalLayout_7.addWidget(self.pushButton_SelectedDevice_VideoClean)
        spacerItem2 = QtWidgets.QSpacerItem(689, 22, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem2)
        self.verticalLayout_5.addWidget(self.frame_5)
        self.frame_4 = QtWidgets.QFrame(self.tabSelected)
        self.frame_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_6.setContentsMargins(0, 5, 0, 5)
        self.horizontalLayout_6.setSpacing(6)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.pushButton_SelectedDevice_Reboot = QtWidgets.QPushButton(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_SelectedDevice_Reboot.sizePolicy().hasHeightForWidth())
        self.pushButton_SelectedDevice_Reboot.setSizePolicy(sizePolicy)
        self.pushButton_SelectedDevice_Reboot.setMinimumSize(QtCore.QSize(88, 0))
        self.pushButton_SelectedDevice_Reboot.setObjectName("pushButton_SelectedDevice_Reboot")
        self.horizontalLayout_6.addWidget(self.pushButton_SelectedDevice_Reboot)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.verticalLayout_5.addWidget(self.frame_4)
        spacerItem4 = QtWidgets.QSpacerItem(20, 283, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem4)
        self.tabWidget.addTab(self.tabSelected, "")
        self.tabBatch = QtWidgets.QWidget()
        self.tabBatch.setObjectName("tabBatch")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tabBatch)
        self.verticalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.treeWidget_BatchDevices = QtWidgets.QTreeWidget(self.tabBatch)
        self.treeWidget_BatchDevices.setUniformRowHeights(True)
        self.treeWidget_BatchDevices.setAllColumnsShowFocus(True)
        self.treeWidget_BatchDevices.setObjectName("treeWidget_BatchDevices")
        self.verticalLayout_3.addWidget(self.treeWidget_BatchDevices)
        self.frame_6 = QtWidgets.QFrame(self.tabBatch)
        self.frame_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_8.setContentsMargins(0, 5, 0, 0)
        self.horizontalLayout_8.setSpacing(6)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.pushButton_Batch_SelectAll = QtWidgets.QPushButton(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_Batch_SelectAll.sizePolicy().hasHeightForWidth())
        self.pushButton_Batch_SelectAll.setSizePolicy(sizePolicy)
        self.pushButton_Batch_SelectAll.setMinimumSize(QtCore.QSize(88, 0))
        self.pushButton_Batch_SelectAll.setObjectName("pushButton_Batch_SelectAll")
        self.horizontalLayout_8.addWidget(self.pushButton_Batch_SelectAll)
        self.pushButton_Batch_SelectActive = QtWidgets.QPushButton(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_Batch_SelectActive.sizePolicy().hasHeightForWidth())
        self.pushButton_Batch_SelectActive.setSizePolicy(sizePolicy)
        self.pushButton_Batch_SelectActive.setMinimumSize(QtCore.QSize(88, 0))
        self.pushButton_Batch_SelectActive.setObjectName("pushButton_Batch_SelectActive")
        self.horizontalLayout_8.addWidget(self.pushButton_Batch_SelectActive)
        self.pushButton_Batch_SelectNone = QtWidgets.QPushButton(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_Batch_SelectNone.sizePolicy().hasHeightForWidth())
        self.pushButton_Batch_SelectNone.setSizePolicy(sizePolicy)
        self.pushButton_Batch_SelectNone.setMinimumSize(QtCore.QSize(88, 0))
        self.pushButton_Batch_SelectNone.setObjectName("pushButton_Batch_SelectNone")
        self.horizontalLayout_8.addWidget(self.pushButton_Batch_SelectNone)
        spacerItem5 = QtWidgets.QSpacerItem(501, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem5)
        self.pushButton_Batch_ClearStatus = QtWidgets.QPushButton(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_Batch_ClearStatus.sizePolicy().hasHeightForWidth())
        self.pushButton_Batch_ClearStatus.setSizePolicy(sizePolicy)
        self.pushButton_Batch_ClearStatus.setMinimumSize(QtCore.QSize(88, 0))
        self.pushButton_Batch_ClearStatus.setObjectName("pushButton_Batch_ClearStatus")
        self.horizontalLayout_8.addWidget(self.pushButton_Batch_ClearStatus)
        self.verticalLayout_3.addWidget(self.frame_6)
        self.frame_7 = QtWidgets.QFrame(self.tabBatch)
        self.frame_7.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_9.setContentsMargins(0, 5, 0, 0)
        self.horizontalLayout_9.setSpacing(6)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.pushButton_Batch_AudioUpdate = QtWidgets.QPushButton(self.frame_7)
        self.pushButton_Batch_AudioUpdate.setMinimumSize(QtCore.QSize(88, 0))
        self.pushButton_Batch_AudioUpdate.setObjectName("pushButton_Batch_AudioUpdate")
        self.horizontalLayout_9.addWidget(self.pushButton_Batch_AudioUpdate)
        self.pushButton_Batch_AudioClean = QtWidgets.QPushButton(self.frame_7)
        self.pushButton_Batch_AudioClean.setMinimumSize(QtCore.QSize(88, 0))
        self.pushButton_Batch_AudioClean.setObjectName("pushButton_Batch_AudioClean")
        self.horizontalLayout_9.addWidget(self.pushButton_Batch_AudioClean)
        spacerItem6 = QtWidgets.QSpacerItem(44, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem6)
        self.pushButton_Batch_VideoUpdate = QtWidgets.QPushButton(self.frame_7)
        self.pushButton_Batch_VideoUpdate.setMinimumSize(QtCore.QSize(88, 0))
        self.pushButton_Batch_VideoUpdate.setObjectName("pushButton_Batch_VideoUpdate")
        self.horizontalLayout_9.addWidget(self.pushButton_Batch_VideoUpdate)
        self.pushButton_Batch_VideoClean = QtWidgets.QPushButton(self.frame_7)
        self.pushButton_Batch_VideoClean.setMinimumSize(QtCore.QSize(88, 0))
        self.pushButton_Batch_VideoClean.setObjectName("pushButton_Batch_VideoClean")
        self.horizontalLayout_9.addWidget(self.pushButton_Batch_VideoClean)
        spacerItem7 = QtWidgets.QSpacerItem(44, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem7)
        self.checkBox_Batch_CleanAfterUpdate = QtWidgets.QCheckBox(self.frame_7)
        self.checkBox_Batch_CleanAfterUpdate.setObjectName("checkBox_Batch_CleanAfterUpdate")
        self.horizontalLayout_9.addWidget(self.checkBox_Batch_CleanAfterUpdate)
        spacerItem8 = QtWidgets.QSpacerItem(162, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem8)
        self.pushButton_Batch_PingVersion = QtWidgets.QPushButton(self.frame_7)
        self.pushButton_Batch_PingVersion.setMinimumSize(QtCore.QSize(88, 0))
        self.pushButton_Batch_PingVersion.setObjectName("pushButton_Batch_PingVersion")
        self.horizontalLayout_9.addWidget(self.pushButton_Batch_PingVersion)
        self.verticalLayout_3.addWidget(self.frame_7)
        self.tabWidget.addTab(self.tabBatch, "")
        self.tabMovies = QtWidgets.QWidget()
        self.tabMovies.setObjectName("tabMovies")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tabMovies)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.treeWidget_Movies = QtWidgets.QTreeWidget(self.tabMovies)
        self.treeWidget_Movies.setUniformRowHeights(True)
        self.treeWidget_Movies.setAllColumnsShowFocus(True)
        self.treeWidget_Movies.setObjectName("treeWidget_Movies")
        self.verticalLayout.addWidget(self.treeWidget_Movies)
        self.frame_8 = QtWidgets.QFrame(self.tabMovies)
        self.frame_8.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_Movies_List = QtWidgets.QPushButton(self.frame_8)
        self.pushButton_Movies_List.setObjectName("pushButton_Movies_List")
        self.horizontalLayout_2.addWidget(self.pushButton_Movies_List)
        spacerItem9 = QtWidgets.QSpacerItem(262, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem9)
        self.pushButton_Movies_SelectAll = QtWidgets.QPushButton(self.frame_8)
        self.pushButton_Movies_SelectAll.setObjectName("pushButton_Movies_SelectAll")
        self.horizontalLayout_2.addWidget(self.pushButton_Movies_SelectAll)
        self.pushButton_Movies_SelectNone = QtWidgets.QPushButton(self.frame_8)
        self.pushButton_Movies_SelectNone.setObjectName("pushButton_Movies_SelectNone")
        self.horizontalLayout_2.addWidget(self.pushButton_Movies_SelectNone)
        spacerItem10 = QtWidgets.QSpacerItem(262, 22, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem10)
        self.pushButton_Movies_Refresh = QtWidgets.QPushButton(self.frame_8)
        self.pushButton_Movies_Refresh.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_Movies_Refresh.setObjectName("pushButton_Movies_Refresh")
        self.horizontalLayout_2.addWidget(self.pushButton_Movies_Refresh)
        self.verticalLayout.addWidget(self.frame_8)
        self.tabWidget.addTab(self.tabMovies, "")
        self.tabTV = QtWidgets.QWidget()
        self.tabTV.setObjectName("tabTV")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tabTV)
        self.verticalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.treeWidget_TVShows = QtWidgets.QTreeWidget(self.tabTV)
        self.treeWidget_TVShows.setUniformRowHeights(True)
        self.treeWidget_TVShows.setAllColumnsShowFocus(True)
        self.treeWidget_TVShows.setObjectName("treeWidget_TVShows")
        self.verticalLayout_2.addWidget(self.treeWidget_TVShows)
        self.frame_9 = QtWidgets.QFrame(self.tabTV)
        self.frame_9.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_TV_List = QtWidgets.QPushButton(self.frame_9)
        self.pushButton_TV_List.setObjectName("pushButton_TV_List")
        self.horizontalLayout_3.addWidget(self.pushButton_TV_List)
        spacerItem11 = QtWidgets.QSpacerItem(219, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem11)
        self.pushButton_TV_SelectAll = QtWidgets.QPushButton(self.frame_9)
        self.pushButton_TV_SelectAll.setObjectName("pushButton_TV_SelectAll")
        self.horizontalLayout_3.addWidget(self.pushButton_TV_SelectAll)
        self.pushButton_TV_SelectNone = QtWidgets.QPushButton(self.frame_9)
        self.pushButton_TV_SelectNone.setObjectName("pushButton_TV_SelectNone")
        self.horizontalLayout_3.addWidget(self.pushButton_TV_SelectNone)
        spacerItem12 = QtWidgets.QSpacerItem(219, 22, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem12)
        self.pushButton_TV_Refresh = QtWidgets.QPushButton(self.frame_9)
        self.pushButton_TV_Refresh.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_TV_Refresh.setObjectName("pushButton_TV_Refresh")
        self.horizontalLayout_3.addWidget(self.pushButton_TV_Refresh)
        self.pushButton_TV_RefreshAll = QtWidgets.QPushButton(self.frame_9)
        self.pushButton_TV_RefreshAll.setObjectName("pushButton_TV_RefreshAll")
        self.horizontalLayout_3.addWidget(self.pushButton_TV_RefreshAll)
        self.verticalLayout_2.addWidget(self.frame_9)
        self.tabWidget.addTab(self.tabTV, "")
        self.tabLog = QtWidgets.QWidget()
        self.tabLog.setObjectName("tabLog")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tabLog)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setHorizontalSpacing(0)
        self.gridLayout_3.setVerticalSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frameLog = QtWidgets.QFrame(self.tabLog)
        self.frameLog.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frameLog.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameLog.setObjectName("frameLog")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frameLog)
        self.verticalLayout_4.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.listWidget_Log = QtWidgets.QListWidget(self.frameLog)
        self.listWidget_Log.setObjectName("listWidget_Log")
        self.verticalLayout_4.addWidget(self.listWidget_Log)
        self.frame = QtWidgets.QFrame(self.frameLog)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_Log_Clear = QtWidgets.QPushButton(self.frame)
        self.pushButton_Log_Clear.setObjectName("pushButton_Log_Clear")
        self.horizontalLayout.addWidget(self.pushButton_Log_Clear)
        spacerItem13 = QtWidgets.QSpacerItem(597, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem13)
        self.verticalLayout_4.addWidget(self.frame)
        self.gridLayout_3.addWidget(self.frameLog, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabLog, "")
        self.gridLayout.addWidget(self.tabWidget, 1, 0, 1, 5)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 920, 22))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.menuFile.addAction(self.actionQuit)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.label_SelectDevice.setBuddy(self.comboBox_SelectDevice)
        self.label_IpAddress.setBuddy(self.comboBox_SelectDevice)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.comboBox_SelectDevice, self.pushButton_SelectedDevice_Ping)
        MainWindow.setTabOrder(self.pushButton_SelectedDevice_Ping, self.tabWidget)
        MainWindow.setTabOrder(self.tabWidget, self.treeWidget_TVShows)
        MainWindow.setTabOrder(self.treeWidget_TVShows, self.treeWidget_Movies)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Kodi Remote Control"))
        self.pushButton_SelectedDevice_WakeUp.setToolTip(_translate("MainWindow", "Tells Kodi to reboot the selected device."))
        self.pushButton_SelectedDevice_WakeUp.setText(_translate("MainWindow", "Wake Up"))
        self.label_SelectDevice.setText(_translate("MainWindow", "Select Device"))
        self.label_IpAddress.setText(_translate("MainWindow", "IP Address"))
        self.pushButton_SelectedDevice_Ping.setToolTip(_translate("MainWindow", "Ping the selected device.  This will make sure the application can communicate with Kodi."))
        self.pushButton_SelectedDevice_Ping.setText(_translate("MainWindow", "Ping"))
        self.pushButton_SelectedDevice_Version.setToolTip(_translate("MainWindow", "Returns the Kodi version and the JSON version for the selected device."))
        self.pushButton_SelectedDevice_Version.setText(_translate("MainWindow", "Version"))
        self.pushButton_SelectedDevice_UpdateStatus.setToolTip(_translate("MainWindow", "Determine if an audio scan or a video scan is running."))
        self.pushButton_SelectedDevice_UpdateStatus.setText(_translate("MainWindow", "Scan Status"))
        self.pushButton_SelectedDevice_AudioUpdate.setToolTip(_translate("MainWindow", "Update the audio library.  This will import any new music.  It will not update existing items."))
        self.pushButton_SelectedDevice_AudioUpdate.setText(_translate("MainWindow", "Audio Update"))
        self.pushButton_SelectedDevice_AudioClean.setToolTip(_translate("MainWindow", "Clean the audio library.  This will remove any deleted or missing items from the library."))
        self.pushButton_SelectedDevice_AudioClean.setText(_translate("MainWindow", "Audio Clean"))
        self.pushButton_SelectedDevice_VideoUpdate.setToolTip(_translate("MainWindow", "Update the video library.  This will import any new movies, TV shows and episodes.  It will not update existing items."))
        self.pushButton_SelectedDevice_VideoUpdate.setText(_translate("MainWindow", "Video Update"))
        self.pushButton_SelectedDevice_VideoClean.setToolTip(_translate("MainWindow", "Clean the video library.  This will remove any deleted or missing items from the library."))
        self.pushButton_SelectedDevice_VideoClean.setText(_translate("MainWindow", "Video Clean"))
        self.pushButton_SelectedDevice_Reboot.setToolTip(_translate("MainWindow", "Tells Kodi to reboot the selected device."))
        self.pushButton_SelectedDevice_Reboot.setText(_translate("MainWindow", "Reboot"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabSelected), _translate("MainWindow", "Selected"))
        self.treeWidget_BatchDevices.headerItem().setText(0, _translate("MainWindow", "Key"))
        self.treeWidget_BatchDevices.headerItem().setText(1, _translate("MainWindow", "Device"))
        self.treeWidget_BatchDevices.headerItem().setText(2, _translate("MainWindow", "Status"))
        self.pushButton_Batch_SelectAll.setToolTip(_translate("MainWindow", "Select (check) all batch update devices."))
        self.pushButton_Batch_SelectAll.setText(_translate("MainWindow", "Select All"))
        self.pushButton_Batch_SelectActive.setToolTip(_translate("MainWindow", "Select (check) only the batch update devices defined as \'active\'."))
        self.pushButton_Batch_SelectActive.setText(_translate("MainWindow", "Select Active"))
        self.pushButton_Batch_SelectNone.setToolTip(_translate("MainWindow", "Un-select (un-check) all batch devices."))
        self.pushButton_Batch_SelectNone.setText(_translate("MainWindow", "Select None"))
        self.pushButton_Batch_ClearStatus.setToolTip(_translate("MainWindow", "Clear the status column for all batch devices."))
        self.pushButton_Batch_ClearStatus.setText(_translate("MainWindow", "Clear Status"))
        self.pushButton_Batch_AudioUpdate.setToolTip(_translate("MainWindow", "Batch update the audio for the checked devices.  Each device will be updated in turn,"))
        self.pushButton_Batch_AudioUpdate.setText(_translate("MainWindow", "Audio Update"))
        self.pushButton_Batch_AudioClean.setToolTip(_translate("MainWindow", "Batch update the audio for the checked devices.  Each device will be updated in turn,"))
        self.pushButton_Batch_AudioClean.setText(_translate("MainWindow", "Audio Clean"))
        self.pushButton_Batch_VideoUpdate.setToolTip(_translate("MainWindow", "Batch update the video for the checked devices.  Each device will be updated in turn,"))
        self.pushButton_Batch_VideoUpdate.setText(_translate("MainWindow", "Video Update"))
        self.pushButton_Batch_VideoClean.setToolTip(_translate("MainWindow", "Batch update the video for the checked devices.  Each device will be updated in turn,"))
        self.pushButton_Batch_VideoClean.setText(_translate("MainWindow", "Video Clean"))
        self.checkBox_Batch_CleanAfterUpdate.setText(_translate("MainWindow", "Clean after update"))
        self.pushButton_Batch_PingVersion.setToolTip(_translate("MainWindow", "Ping the selected devices; then get the kodi & json versions."))
        self.pushButton_Batch_PingVersion.setText(_translate("MainWindow", "Ping && Version"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabBatch), _translate("MainWindow", "Batch"))
        self.treeWidget_Movies.headerItem().setText(0, _translate("MainWindow", "ID #"))
        self.treeWidget_Movies.headerItem().setText(1, _translate("MainWindow", "Title"))
        self.treeWidget_Movies.headerItem().setText(2, _translate("MainWindow", "Year"))
        self.pushButton_Movies_List.setToolTip(_translate("MainWindow", "Get a list of movies from the selected device."))
        self.pushButton_Movies_List.setText(_translate("MainWindow", "List"))
        self.pushButton_Movies_SelectAll.setToolTip(_translate("MainWindow", "Select (check) all movies in the list."))
        self.pushButton_Movies_SelectAll.setText(_translate("MainWindow", "Select All"))
        self.pushButton_Movies_SelectNone.setToolTip(_translate("MainWindow", "Un-select (un-check) all movies in the list."))
        self.pushButton_Movies_SelectNone.setText(_translate("MainWindow", "Select None"))
        self.pushButton_Movies_Refresh.setToolTip(_translate("MainWindow", "Refresh (re-import) all of the checked movies in the list."))
        self.pushButton_Movies_Refresh.setText(_translate("MainWindow", "Refresh"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabMovies), _translate("MainWindow", "Movies"))
        self.treeWidget_TVShows.headerItem().setText(0, _translate("MainWindow", "ID #"))
        self.treeWidget_TVShows.headerItem().setText(1, _translate("MainWindow", "Title"))
        self.treeWidget_TVShows.headerItem().setText(2, _translate("MainWindow", "Year"))
        self.pushButton_TV_List.setToolTip(_translate("MainWindow", "Get a list of all TV shows, by season and episodes, from the selected device."))
        self.pushButton_TV_List.setText(_translate("MainWindow", "List"))
        self.pushButton_TV_SelectAll.setToolTip(_translate("MainWindow", "Select (check) all of the TV shows in the list."))
        self.pushButton_TV_SelectAll.setText(_translate("MainWindow", "Select All"))
        self.pushButton_TV_SelectNone.setToolTip(_translate("MainWindow", "Un-select (un-check) all of the TV sjhows in the list."))
        self.pushButton_TV_SelectNone.setText(_translate("MainWindow", "Select None"))
        self.pushButton_TV_Refresh.setToolTip(_translate("MainWindow", "Refresh (re-import) all of the checked TV shows in the list.  This does not refresh the episodes."))
        self.pushButton_TV_Refresh.setText(_translate("MainWindow", "Refresh"))
        self.pushButton_TV_RefreshAll.setToolTip(_translate("MainWindow", "Refresh (re-import) all of the check TV shows in the list.  This will also refresh the episodes."))
        self.pushButton_TV_RefreshAll.setText(_translate("MainWindow", "Refresh All"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabTV), _translate("MainWindow", "TV"))
        self.pushButton_Log_Clear.setText(_translate("MainWindow", "Clear"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabLog), _translate("MainWindow", "Log"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))

