# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(720, 480)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout.setContentsMargins(11, 11, 11, 0)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.label_SelectDevice = QtWidgets.QLabel(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_SelectDevice.sizePolicy().hasHeightForWidth())
        self.label_SelectDevice.setSizePolicy(sizePolicy)
        self.label_SelectDevice.setObjectName("label_SelectDevice")
        self.gridLayout.addWidget(self.label_SelectDevice, 0, 0, 1, 1)
        self.comboBox_SelectDevice = QtWidgets.QComboBox(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_SelectDevice.sizePolicy().hasHeightForWidth())
        self.comboBox_SelectDevice.setSizePolicy(sizePolicy)
        self.comboBox_SelectDevice.setEditable(False)
        self.comboBox_SelectDevice.setObjectName("comboBox_SelectDevice")
        self.gridLayout.addWidget(self.comboBox_SelectDevice, 0, 1, 1, 1)
        self.label_IpAddress = QtWidgets.QLabel(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_IpAddress.sizePolicy().hasHeightForWidth())
        self.label_IpAddress.setSizePolicy(sizePolicy)
        self.label_IpAddress.setMinimumSize(QtCore.QSize(0, 0))
        self.label_IpAddress.setMaximumSize(QtCore.QSize(120, 16777215))
        self.label_IpAddress.setObjectName("label_IpAddress")
        self.gridLayout.addWidget(self.label_IpAddress, 0, 2, 1, 1)
        self.pushButton_SelectedDevice_Reboot = QtWidgets.QPushButton(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_SelectedDevice_Reboot.sizePolicy().hasHeightForWidth())
        self.pushButton_SelectedDevice_Reboot.setSizePolicy(sizePolicy)
        self.pushButton_SelectedDevice_Reboot.setObjectName("pushButton_SelectedDevice_Reboot")
        self.gridLayout.addWidget(self.pushButton_SelectedDevice_Reboot, 0, 3, 1, 1)
        self.pushButton_SelectedDevice_Version = QtWidgets.QPushButton(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_SelectedDevice_Version.sizePolicy().hasHeightForWidth())
        self.pushButton_SelectedDevice_Version.setSizePolicy(sizePolicy)
        self.pushButton_SelectedDevice_Version.setObjectName("pushButton_SelectedDevice_Version")
        self.gridLayout.addWidget(self.pushButton_SelectedDevice_Version, 0, 4, 1, 1)
        self.pushButton_SelectedDevice_Ping = QtWidgets.QPushButton(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_SelectedDevice_Ping.sizePolicy().hasHeightForWidth())
        self.pushButton_SelectedDevice_Ping.setSizePolicy(sizePolicy)
        self.pushButton_SelectedDevice_Ping.setFlat(False)
        self.pushButton_SelectedDevice_Ping.setObjectName("pushButton_SelectedDevice_Ping")
        self.gridLayout.addWidget(self.pushButton_SelectedDevice_Ping, 0, 5, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName("tabWidget")
        self.tabVideo = QtWidgets.QWidget()
        self.tabVideo.setObjectName("tabVideo")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tabVideo)
        self.verticalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox_SelectedDevice = QtWidgets.QGroupBox(self.tabVideo)
        self.groupBox_SelectedDevice.setFlat(False)
        self.groupBox_SelectedDevice.setCheckable(False)
        self.groupBox_SelectedDevice.setObjectName("groupBox_SelectedDevice")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.groupBox_SelectedDevice)
        self.horizontalLayout_5.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_5.setSpacing(6)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pushButton_SelectedDevice_VideoUpdate = QtWidgets.QPushButton(self.groupBox_SelectedDevice)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_SelectedDevice_VideoUpdate.sizePolicy().hasHeightForWidth())
        self.pushButton_SelectedDevice_VideoUpdate.setSizePolicy(sizePolicy)
        self.pushButton_SelectedDevice_VideoUpdate.setObjectName("pushButton_SelectedDevice_VideoUpdate")
        self.horizontalLayout_5.addWidget(self.pushButton_SelectedDevice_VideoUpdate)
        self.pushButton_SelectedDevice_VideoClean = QtWidgets.QPushButton(self.groupBox_SelectedDevice)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_SelectedDevice_VideoClean.sizePolicy().hasHeightForWidth())
        self.pushButton_SelectedDevice_VideoClean.setSizePolicy(sizePolicy)
        self.pushButton_SelectedDevice_VideoClean.setObjectName("pushButton_SelectedDevice_VideoClean")
        self.horizontalLayout_5.addWidget(self.pushButton_SelectedDevice_VideoClean)
        spacerItem = QtWidgets.QSpacerItem(481, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.verticalLayout_3.addWidget(self.groupBox_SelectedDevice)
        self.groupBox_BatchUpdate = QtWidgets.QGroupBox(self.tabVideo)
        self.groupBox_BatchUpdate.setObjectName("groupBox_BatchUpdate")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_BatchUpdate)
        self.gridLayout_2.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.treeWidget_BatchUpdate = QtWidgets.QTreeWidget(self.groupBox_BatchUpdate)
        self.treeWidget_BatchUpdate.setUniformRowHeights(True)
        self.treeWidget_BatchUpdate.setAllColumnsShowFocus(True)
        self.treeWidget_BatchUpdate.setObjectName("treeWidget_BatchUpdate")
        self.gridLayout_2.addWidget(self.treeWidget_BatchUpdate, 0, 0, 1, 7)
        self.pushButton_Batch_SelectAll = QtWidgets.QPushButton(self.groupBox_BatchUpdate)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_Batch_SelectAll.sizePolicy().hasHeightForWidth())
        self.pushButton_Batch_SelectAll.setSizePolicy(sizePolicy)
        self.pushButton_Batch_SelectAll.setObjectName("pushButton_Batch_SelectAll")
        self.gridLayout_2.addWidget(self.pushButton_Batch_SelectAll, 1, 0, 1, 1)
        self.pushButton_Batch_SelectActive = QtWidgets.QPushButton(self.groupBox_BatchUpdate)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_Batch_SelectActive.sizePolicy().hasHeightForWidth())
        self.pushButton_Batch_SelectActive.setSizePolicy(sizePolicy)
        self.pushButton_Batch_SelectActive.setObjectName("pushButton_Batch_SelectActive")
        self.gridLayout_2.addWidget(self.pushButton_Batch_SelectActive, 1, 1, 1, 1)
        self.pushButton_Batch_SelectNone = QtWidgets.QPushButton(self.groupBox_BatchUpdate)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_Batch_SelectNone.sizePolicy().hasHeightForWidth())
        self.pushButton_Batch_SelectNone.setSizePolicy(sizePolicy)
        self.pushButton_Batch_SelectNone.setObjectName("pushButton_Batch_SelectNone")
        self.gridLayout_2.addWidget(self.pushButton_Batch_SelectNone, 1, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(223, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 1, 3, 1, 1)
        self.pushButton_Batch_ClearStatus = QtWidgets.QPushButton(self.groupBox_BatchUpdate)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_Batch_ClearStatus.sizePolicy().hasHeightForWidth())
        self.pushButton_Batch_ClearStatus.setSizePolicy(sizePolicy)
        self.pushButton_Batch_ClearStatus.setObjectName("pushButton_Batch_ClearStatus")
        self.gridLayout_2.addWidget(self.pushButton_Batch_ClearStatus, 1, 4, 1, 1)
        self.pushButton_Batch_Update = QtWidgets.QPushButton(self.groupBox_BatchUpdate)
        self.pushButton_Batch_Update.setObjectName("pushButton_Batch_Update")
        self.gridLayout_2.addWidget(self.pushButton_Batch_Update, 1, 5, 1, 1)
        self.pushButton_Batch_PingVersion = QtWidgets.QPushButton(self.groupBox_BatchUpdate)
        self.pushButton_Batch_PingVersion.setObjectName("pushButton_Batch_PingVersion")
        self.gridLayout_2.addWidget(self.pushButton_Batch_PingVersion, 1, 6, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox_BatchUpdate)
        self.tabWidget.addTab(self.tabVideo, "")
        self.tabMovies = QtWidgets.QWidget()
        self.tabMovies.setObjectName("tabMovies")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tabMovies)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.treeWidget_Movies = QtWidgets.QTreeWidget(self.tabMovies)
        self.treeWidget_Movies.setUniformRowHeights(True)
        self.treeWidget_Movies.setAllColumnsShowFocus(True)
        self.treeWidget_Movies.setObjectName("treeWidget_Movies")
        self.verticalLayout.addWidget(self.treeWidget_Movies)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_Movies_List = QtWidgets.QPushButton(self.tabMovies)
        self.pushButton_Movies_List.setObjectName("pushButton_Movies_List")
        self.horizontalLayout_2.addWidget(self.pushButton_Movies_List)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.pushButton_Movies_SelectAll = QtWidgets.QPushButton(self.tabMovies)
        self.pushButton_Movies_SelectAll.setObjectName("pushButton_Movies_SelectAll")
        self.horizontalLayout_2.addWidget(self.pushButton_Movies_SelectAll)
        self.pushButton_Movies_SelectNone = QtWidgets.QPushButton(self.tabMovies)
        self.pushButton_Movies_SelectNone.setObjectName("pushButton_Movies_SelectNone")
        self.horizontalLayout_2.addWidget(self.pushButton_Movies_SelectNone)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.pushButton_Movies_Refresh = QtWidgets.QPushButton(self.tabMovies)
        self.pushButton_Movies_Refresh.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_Movies_Refresh.setObjectName("pushButton_Movies_Refresh")
        self.horizontalLayout_2.addWidget(self.pushButton_Movies_Refresh)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.tabWidget.addTab(self.tabMovies, "")
        self.tabTV = QtWidgets.QWidget()
        self.tabTV.setObjectName("tabTV")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tabTV)
        self.verticalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.treeWidget_TVShows = QtWidgets.QTreeWidget(self.tabTV)
        self.treeWidget_TVShows.setUniformRowHeights(True)
        self.treeWidget_TVShows.setAllColumnsShowFocus(True)
        self.treeWidget_TVShows.setObjectName("treeWidget_TVShows")
        self.verticalLayout_2.addWidget(self.treeWidget_TVShows)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_TV_List = QtWidgets.QPushButton(self.tabTV)
        self.pushButton_TV_List.setObjectName("pushButton_TV_List")
        self.horizontalLayout_3.addWidget(self.pushButton_TV_List)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.pushButton_TV_SelectAll = QtWidgets.QPushButton(self.tabTV)
        self.pushButton_TV_SelectAll.setObjectName("pushButton_TV_SelectAll")
        self.horizontalLayout_3.addWidget(self.pushButton_TV_SelectAll)
        self.pushButton_TV_SelectNone = QtWidgets.QPushButton(self.tabTV)
        self.pushButton_TV_SelectNone.setObjectName("pushButton_TV_SelectNone")
        self.horizontalLayout_3.addWidget(self.pushButton_TV_SelectNone)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.pushButton_TV_Refresh = QtWidgets.QPushButton(self.tabTV)
        self.pushButton_TV_Refresh.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_TV_Refresh.setObjectName("pushButton_TV_Refresh")
        self.horizontalLayout_3.addWidget(self.pushButton_TV_Refresh)
        self.pushButton_TV_RefreshAll = QtWidgets.QPushButton(self.tabTV)
        self.pushButton_TV_RefreshAll.setObjectName("pushButton_TV_RefreshAll")
        self.horizontalLayout_3.addWidget(self.pushButton_TV_RefreshAll)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.tabWidget.addTab(self.tabTV, "")
        self.gridLayout.addWidget(self.tabWidget, 1, 0, 1, 6)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 720, 22))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.menuFile.addAction(self.actionQuit)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.label_SelectDevice.setBuddy(self.comboBox_SelectDevice)
        self.label_IpAddress.setBuddy(self.comboBox_SelectDevice)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.comboBox_SelectDevice, self.pushButton_SelectedDevice_Ping)
        MainWindow.setTabOrder(self.pushButton_SelectedDevice_Ping, self.tabWidget)
        MainWindow.setTabOrder(self.tabWidget, self.pushButton_Movies_List)
        MainWindow.setTabOrder(self.pushButton_Movies_List, self.pushButton_SelectedDevice_VideoUpdate)
        MainWindow.setTabOrder(self.pushButton_SelectedDevice_VideoUpdate, self.pushButton_SelectedDevice_VideoClean)
        MainWindow.setTabOrder(self.pushButton_SelectedDevice_VideoClean, self.pushButton_Movies_Refresh)
        MainWindow.setTabOrder(self.pushButton_Movies_Refresh, self.pushButton_Movies_SelectAll)
        MainWindow.setTabOrder(self.pushButton_Movies_SelectAll, self.pushButton_Movies_SelectNone)
        MainWindow.setTabOrder(self.pushButton_Movies_SelectNone, self.treeWidget_TVShows)
        MainWindow.setTabOrder(self.treeWidget_TVShows, self.treeWidget_Movies)
        MainWindow.setTabOrder(self.treeWidget_Movies, self.pushButton_TV_List)
        MainWindow.setTabOrder(self.pushButton_TV_List, self.pushButton_TV_SelectAll)
        MainWindow.setTabOrder(self.pushButton_TV_SelectAll, self.pushButton_TV_SelectNone)
        MainWindow.setTabOrder(self.pushButton_TV_SelectNone, self.pushButton_TV_Refresh)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Kodi Remote Control"))
        self.label_SelectDevice.setText(_translate("MainWindow", "Select Device"))
        self.label_IpAddress.setText(_translate("MainWindow", "IP Address"))
        self.pushButton_SelectedDevice_Reboot.setToolTip(_translate("MainWindow", "Tells Kodi to reboot the selected device."))
        self.pushButton_SelectedDevice_Reboot.setText(_translate("MainWindow", "Reboot"))
        self.pushButton_SelectedDevice_Version.setToolTip(_translate("MainWindow", "Returns the Kodi version and the JSON version for the selected device."))
        self.pushButton_SelectedDevice_Version.setText(_translate("MainWindow", "Version"))
        self.pushButton_SelectedDevice_Ping.setToolTip(_translate("MainWindow", "Ping the selected device.  This will make sure the application can communicate with Kodi."))
        self.pushButton_SelectedDevice_Ping.setText(_translate("MainWindow", "Ping"))
        self.groupBox_SelectedDevice.setTitle(_translate("MainWindow", "Selected Device"))
        self.pushButton_SelectedDevice_VideoUpdate.setToolTip(_translate("MainWindow", "Update the video library.  This will import any new movies, TV shows and episodes.  It will not update existing items."))
        self.pushButton_SelectedDevice_VideoUpdate.setText(_translate("MainWindow", "Update"))
        self.pushButton_SelectedDevice_VideoClean.setToolTip(_translate("MainWindow", "Clean the video library.  This will remove any deleted or missing items from the library."))
        self.pushButton_SelectedDevice_VideoClean.setText(_translate("MainWindow", "Clean"))
        self.groupBox_BatchUpdate.setTitle(_translate("MainWindow", "Batch Update"))
        self.treeWidget_BatchUpdate.headerItem().setText(0, _translate("MainWindow", "Key"))
        self.treeWidget_BatchUpdate.headerItem().setText(1, _translate("MainWindow", "Device"))
        self.treeWidget_BatchUpdate.headerItem().setText(2, _translate("MainWindow", "Status"))
        self.pushButton_Batch_SelectAll.setToolTip(_translate("MainWindow", "Select (check) all batch update devices."))
        self.pushButton_Batch_SelectAll.setText(_translate("MainWindow", "Select All"))
        self.pushButton_Batch_SelectActive.setToolTip(_translate("MainWindow", "Select (check) only the batch update devices defined as \'active\'."))
        self.pushButton_Batch_SelectActive.setText(_translate("MainWindow", "Select Active"))
        self.pushButton_Batch_SelectNone.setToolTip(_translate("MainWindow", "Un-select (un-check) all batch devices."))
        self.pushButton_Batch_SelectNone.setText(_translate("MainWindow", "Select None"))
        self.pushButton_Batch_ClearStatus.setToolTip(_translate("MainWindow", "Clear the batch update status column."))
        self.pushButton_Batch_ClearStatus.setText(_translate("MainWindow", "Clear Status"))
        self.pushButton_Batch_Update.setToolTip(_translate("MainWindow", "Batch update the checked devices.  Each device will be updated in turn,"))
        self.pushButton_Batch_Update.setText(_translate("MainWindow", "Update"))
        self.pushButton_Batch_PingVersion.setToolTip(_translate("MainWindow", "Ping the selected devices; then get the kodi & json versions."))
        self.pushButton_Batch_PingVersion.setText(_translate("MainWindow", "Ping && Version"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabVideo), _translate("MainWindow", "Video"))
        self.treeWidget_Movies.headerItem().setText(0, _translate("MainWindow", "ID #"))
        self.treeWidget_Movies.headerItem().setText(1, _translate("MainWindow", "Title"))
        self.treeWidget_Movies.headerItem().setText(2, _translate("MainWindow", "Year"))
        self.pushButton_Movies_List.setToolTip(_translate("MainWindow", "Get a list of movies from the selected device."))
        self.pushButton_Movies_List.setText(_translate("MainWindow", "List"))
        self.pushButton_Movies_SelectAll.setToolTip(_translate("MainWindow", "Select (check) all movies in the list."))
        self.pushButton_Movies_SelectAll.setText(_translate("MainWindow", "Select All"))
        self.pushButton_Movies_SelectNone.setToolTip(_translate("MainWindow", "Un-select (un-check) all movies in the list."))
        self.pushButton_Movies_SelectNone.setText(_translate("MainWindow", "Select None"))
        self.pushButton_Movies_Refresh.setToolTip(_translate("MainWindow", "Refresh (re-import) all of the checked movies in the list."))
        self.pushButton_Movies_Refresh.setText(_translate("MainWindow", "Refresh"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabMovies), _translate("MainWindow", "Movies"))
        self.treeWidget_TVShows.headerItem().setText(0, _translate("MainWindow", "ID #"))
        self.treeWidget_TVShows.headerItem().setText(1, _translate("MainWindow", "Title"))
        self.treeWidget_TVShows.headerItem().setText(2, _translate("MainWindow", "Year"))
        self.pushButton_TV_List.setToolTip(_translate("MainWindow", "Get a list of all TV shows, by season and episodes, from the selected device."))
        self.pushButton_TV_List.setText(_translate("MainWindow", "List"))
        self.pushButton_TV_SelectAll.setToolTip(_translate("MainWindow", "Select (check) all of the TV shows in the list."))
        self.pushButton_TV_SelectAll.setText(_translate("MainWindow", "Select All"))
        self.pushButton_TV_SelectNone.setToolTip(_translate("MainWindow", "Un-select (un-check) all of the TV sjhows in the list."))
        self.pushButton_TV_SelectNone.setText(_translate("MainWindow", "Select None"))
        self.pushButton_TV_Refresh.setToolTip(_translate("MainWindow", "Refresh (re-import) all of the checked TV shows in the list.  This does not refresh the episodes."))
        self.pushButton_TV_Refresh.setText(_translate("MainWindow", "Refresh"))
        self.pushButton_TV_RefreshAll.setToolTip(_translate("MainWindow", "Refresh (re-import) all of the check TV shows in the list.  This will also refresh the episodes."))
        self.pushButton_TV_RefreshAll.setText(_translate("MainWindow", "Refresh All"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabTV), _translate("MainWindow", "TV"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))

